shell /usr/bin/bash


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.9

font_family      iMWritingMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

remember_window_size  no
initial_window_width  800
initial_window_height 480

font_size 9.0

window_padding_width 0 5 5 5

map ctrl+backspace send_text all \x17

